name: base_template
description: "Flutter project with design system template"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 상태 관리 및 데이터 모델
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # 라우팅
  go_router: ^16.2.1

  # 유틸리티
  intl: ^0.20.2
  shared_preferences: ^2.3.4

  # UI 반응형
  flutter_screenutil: ^5.9.3

  # 이미지 & 아이콘
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1

  # 로딩 애니메이션
  shimmer: ^3.0.0

  # 다국어 지원
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # 코드 생성
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.9.2

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
